//MIT License

//Copyright (c) 2026 Dimon

//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:

//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.

//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.

using HostlistDownloader.Modules.Helpers;
using System.Text.Json;
using System.Text.Json.Serialization;

// Add new namespace for our context
namespace HostlistDownloader.Modules.WindowsSystem
{
    /// <summary>
    /// POCO that mirrors the JSON format exactly.
    /// All properties are internal – only the wrapper in this file exposes them
    /// via read‑only interfaces.  The class is *immutable* after construction,
    /// so callers cannot accidentally modify configuration values.
    /// </summary>
    [JsonSerializable(typeof(Settings))] // Register Settings with JsonSerializerContext
    internal partial class SettingsJsonSerializerContext : JsonSerializerContext
    {
        // This partial class will be auto-generated by the compiler
    }

    internal sealed record Settings(
        [property: JsonPropertyName("blocklists")] string[]? Blocklists = null,
        [property: JsonPropertyName("whitelist")] string[]? Whitelist = null,
        [property: JsonPropertyName("formattype")] string? Formattype = null,
        [property: JsonPropertyName("userWebsiteBlocklist")] string[]? UserWebsiteBlocklist = null,
        [property: JsonPropertyName("userWebsiteWhitelist")] string[]? UserWebsiteWhitelist = null,
        [property: JsonPropertyName("maxDownloadThreads")] int? MaxDownloadThreads = null,
        [property: JsonPropertyName("logExpiryInDays")] int? LogExpiryInDays = null)
    {
        private Settings() : this(null) { } // prevent manual construction
    }

    /// <summary>
    /// Public, read‑only view of the configuration.
    /// </summary>
    public sealed class ConfigReader
    {
        internal static ConfigReader Instance => _instance ?? throw new InvalidOperationException("ConfigReader not yet initialised.");

        private static ConfigReader? _instance;
        public IReadOnlyList<string> Blocklists { get; }
        public IReadOnlyList<string> Whitelist { get; }
        public string Formattype { get; }
        public IReadOnlyList<string> UserWebsiteBlocklist { get; }
        public IReadOnlyList<string> UserWebsiteWhitelist { get; }
        public int MaxDownloadThreads { get; } = 3;
        public int LogExpiryInDays { get; } = 7;

        internal ConfigReader(Settings raw)
        {
            Blocklists = Array.AsReadOnly(raw.Blocklists ?? []);
            Whitelist = Array.AsReadOnly(raw.Whitelist ?? []);
            Formattype = !string.IsNullOrWhiteSpace(raw.Formattype) ? raw.Formattype : "domain";
            UserWebsiteBlocklist = Array.AsReadOnly(raw.UserWebsiteBlocklist ?? []);
            UserWebsiteWhitelist = Array.AsReadOnly(raw.UserWebsiteWhitelist ?? []);

            if (raw.MaxDownloadThreads.HasValue)
                MaxDownloadThreads = raw.MaxDownloadThreads.Value;
            if (raw.LogExpiryInDays.HasValue)
                LogExpiryInDays = raw.LogExpiryInDays.Value;
            _instance = this;
        }

        /// <summary>
        /// Create the global configuration from a JSON file path.
        /// This method may be called only once; subsequent calls will log an error
        /// and ignore the second attempt, keeping immutability guaranteed.
        /// </summary>
        public static void Init(string jsonFilePath)
        {
            if (_instance != null)
                return;

            if (!File.Exists(jsonFilePath))
                throw new FileNotFoundException("Configuration file missing.", jsonFilePath);

            var json = File.ReadAllText(jsonFilePath);

            Settings? raw;
            try
            {
                raw = JsonSerializer.Deserialize(json, SettingsJsonSerializerContext.Default.Settings);
            }
            catch (Exception ex)
            {
                TraceLogger.Log($"Failed to deserialize settings. {ex}", Enums.StatusSeverityType.Fatal, ErrorCodes.ConfigurationCorrupted);
                return;
            }

            if (raw == null)
            {
                TraceLogger.Log($"Deserialized configuration from '{jsonFilePath}' is null.", Enums.StatusSeverityType.Fatal, ErrorCodes.ConfigurationCorrupted);
                return;
            }
            _ = new ConfigReader(raw);
            TraceLogger.Log($"Successfully read {jsonFilePath} settings.");
        }

        public static void CreateDefaultConfig(string filePath)
        {
            var defaultConfig = new Settings
            {
                Blocklists = [],
                Whitelist = [],
                Formattype = "domain",
                UserWebsiteBlocklist = [],
                UserWebsiteWhitelist = [],
                MaxDownloadThreads = 3,
                LogExpiryInDays = 7
            };

            string defaultJson = JsonSerializer.Serialize(
                defaultConfig,
                SettingsJsonSerializerContext.Default.Settings);
            File.WriteAllText(filePath, defaultJson);
        }
    }
}